### ISSUE TITLE
Please push updated code

### ISSUE THREAD

**Issue by ao2** [skagedal/gobject-introspection-tutorial-code#1]
Hi @skagedal,

maybe you forgot to push a more updated version of the code?

I cannot follow all the steps from the tutorial at http://helgo.net/simon/introspection-tutorial/index.xhtml with the current code in this repository.

Thanks,
   Antonio

**Comment by skagedal** [comment]
I believe the version at https://github.com/skagedal/gobject-introspection-tutorial-code is the latest version.

/simon

**Comment by ao2** [comment]
Hi,

I started form the tutorial at http://helgo.net/simon/introspection-tutorial/ which tells to clone from github at https://github.com/skagedal/gobject-introspection-tutorial-code.git

But in this repository I couldn't checkout "stepone", "steptwo", etc.

Then I saw the actual tutorial.txt file and it refers to a repository on gitorious: https://git.gitorious.org/gobject-introspection-tutorial/code.git

When cloning the latter then I can see all the HEADs.

So the master branch seems to be the same on the two repositories, bu the one on github seems to be missing some pieces.

Now I know that I can follow the one on gitorious, but it was confusing at first.

Thanks,
   Antonio

**Comment by skagedal** [comment]
Oh, now I remember!

The problem was that, some time ago, Gitorious was down and the repository was unreachable. So I put it up at Github. But I must have forgotten to push all the branches... :( 

Good to hear that Gitorious is now back again. I will update the page when I find the time. 

Thanks for reporting this!

/simon

**Comment by Hrungnir** [comment]
poke poke 
please push all the branches.

Thanks.

**Comment by AlisaMaas** [comment]
I'm also here via the tutorial. If anyone else is looking for the code still: gitorious seems to currently be down, but I found a mirror. Try https://gitorious.org/gobject-introspection-tutorial/code.git. (That said, pushing all the branches here would be great, since it's the first place people will look -- it's what's linked in the tutorial itself.)

**Comment by erooke** [comment]
Gitorious is having issues with their ssl keys. I pulled all the branches and have pushed them to a fork on my account just to help keep access to them alive.

https://github.com/erooke/gobject-introspection-tutorial-code

I would send prs but it seems you can't pr a new branch

**Comment by skagedal** [comment]
Thanks for the comments! I'm amazed that people are still finding this old thing. I have now pushed all the branches to this repo, cloned from @erooke's clone of my gitorious.
